DROP TABLE IF EXISTS map_id_pin_ids CASCADE;

CREATE TABLE map_id_pin_ids (
  id SERIAL PRIMARY KEY NOT NULL,
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE,
  pin_id INTEGER REFERENCES pins(id) ON DELETE CASCADE
);
