DROP TABLE IF EXISTS map_user_likes CASCADE;

CREATE TABLE map_user_likes (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE,
  likes BOOLEAN DEFAULT FALSE
);
